cmake_minimum_required(VERSION 3.25)
project(WBSFProjects LANGUAGES CXX)

# Optionally enforce C++ standard
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_definitions(-DMUPARSER_STATIC)

IF(MSVC)
    # Add /EHsc to the C++ compiler flags
    # It's important to append it to existing flags, not overwrite them.
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /EHsc") 
ENDIF(MSVC)

# Add -fPIC on Linux/UNIX
if(UNIX AND NOT APPLE)
    set(CMAKE_POSITION_INDEPENDENT_CODE ON)
endif()

# Add subdirectories (order matters: core first)
add_subdirectory(WBSF)
add_subdirectory(WBSFModels)
add_subdirectory(WBSFTools)

# Installation rules
SET(BIOSIM_INSTALL_DIRECTORY ${CMAKE_INSTALL_PREFIX}/$<$<CONFIG:Debug>:Debug>$<$<NOT:$<CONFIG:Debug>>:Release>)
SET(BIOSIM_INSTALL_BIN_DIRECTORY ${BIOSIM_INSTALL_DIRECTORY}/bin)

# install BioSIM_API
install(FILES $<TARGET_FILE_DIR:BioSIM_API>/ DESTINATION ${BIOSIM_INSTALL_BIN_DIRECTORY})
install(FILES $<TARGET_LINKER_FILE:BioSIM_API>/ DESTINATION ${BIOSIM_INSTALL_DIRECTORY}/lib)

get_target_property(BioSIM_INCLUDES BioSIM_API INCLUDE_DIRECTORIES)
install(FILES ${BioSIM_INCLUDES}/BioSIM_API.h DESTINATION ${BIOSIM_INSTALL_DIRECTORY}/include)
get_target_property(WBSF_SOURCE_DIR WBSFBasic SOURCE_DIR)
#message("WBSF_SOURCE_DIR : ${WBSF_SOURCE_DIR}")
install(FILES 
    ${WBSF_SOURCE_DIR}/ERMsg.h 
    DESTINATION ${BIOSIM_INSTALL_DIRECTORY}/include/Basic)
install(FILES     
    ${WBSF_SOURCE_DIR}/ERMsg/Erexcept.h 
    ${WBSF_SOURCE_DIR}/ERMsg/Sycptref.h 
    ${WBSF_SOURCE_DIR}/ERMsg/Sycptref.hpp 
    ${WBSF_SOURCE_DIR}/ERMsg/Syenvmsg.h 
    ${WBSF_SOURCE_DIR}/ERMsg/Symessag.h 
    DESTINATION ${BIOSIM_INSTALL_DIRECTORY}/include/Basic/ERMsg)


#install all model files
set(BIOSIM_INSTALL_BIN_MODELS_DIRECTORY ${BIOSIM_INSTALL_BIN_DIRECTORY}/Models)

install(FILES $<TARGET_FILE_DIR:ActiaInterruptaBiology>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:ASCE-ETc>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:ASCE-ETsz>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:CCBio>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:Climatic>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:ClimaticQc>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:CornHeatUnits>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:DailyVsHourly>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:DailyVsNormals>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:DegreeDay>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:DegreeHour>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:DewPeriod>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:SpringFrost>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:GrowingSeason>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:PotentialEvapotranspiration>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:ReverseDegreeDay>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:SnowMelt>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:SoilTemperature>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:TminTairTmax>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:VaporPressureDeficit>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:WetnessDuration>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:WinterThaw>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})
install(FILES $<TARGET_FILE_DIR:WorldClimVars>/ DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})

# install .mdl files
install(DIRECTORY 
    WBSFInstall/Models/
    DESTINATION ${BIOSIM_INSTALL_BIN_MODELS_DIRECTORY})