name: CMake Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            preset: vs2022-ci
            build-preset: vs2022-ci
          - os: ubuntu-latest
            preset: linux-release
            build-preset: linux-release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0 # Fetches all history for the main repository

      # Install a known-good CMake
      - name: Set up CMake
        uses: lukka/get-cmake@latest
        
      # vcpkg with manifest mode + caching
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: '**/vcpkg.json'
        
      - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-cmake@v10.8
        with:
          configurePreset: ${{ matrix.preset }}

      # Build
      - name: Build
        run: cmake --build --preset=${{ matrix.build-preset }}
